name: address_search_field
description: An address search box that gets nearby addresses by typing a reference, returns an object with place primary data. The object can also find an address using coordinates.
version: 1.4.2
homepage: https://github.com/JosLuna98/address_search_field.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  location: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.jostech.address_search_field
        pluginClass: AddressSearchFieldPlugin
      ios:
        pluginClass: AddressSearchFieldPlugin
